### ISSUE TITLE
Public API can't be used concurrently

### ISSUE THREAD

**Issue by maxcleme** [alexjomin/openapi-parser#46]
Hi,

We are experiencing issue when using the exposed API, with `NewOpenAPI().Parse()`.

We are currently calling this statement in a loop (issue will also be raised if call concurrently), and the `Parse` behavior relies on a global variable call `registeredSchemas`, which is not cleared when `NewOpenAPI()` is call.

In our loop case, schemas of the first `Parse` are still present in the second `Parse`. In a concurrent scenario, schema will be mixed (in a non-deterministic way) and results will also be invalid.

I'll submit a dummy PR in order to encapsulate this type registry inside the `openapi` struct in order to make the whole thing thread-safe.

You can easily reproduce the behavior by running this small snippet :  

```golang
package main

import (
	"io/ioutil"
	"os"

	"github.com/alexjomin/openapi-parser/docparser"
	"gopkg.in/yaml.v2"
)

type Repo struct {
	Name    string
	Path    string
	DocFile string
}

func main() {
	repos := []*Repo{
		{Name: "repo-a", DocFile: "/tmp/repo-a-doc.yaml", Path: "workspace/repo-a"},
		{Name: "repo-b", DocFile: "/tmp/repo-b-doc.yaml", Path: "workspace/repo-b"},
	}
	for _, repo := range repos {
		spec := docparser.NewOpenAPI()
		spec.Parse(repo.Path, []string{}, "vendor", false)

		specYML, err := yaml.Marshal(&spec)
		if err != nil {
			panic(err)
		}
		if err := ioutil.WriteFile(repo.DocFile, specYML, os.ModePerm); err != nil {
			panic(err)
		}

	}
}


```
Schema from `repo-a` will be written in both `/tmp/repo-a-doc.yaml` and `/tmp/repo-b-doc.yaml`.

Cheers.

**Comment by maxcleme** [comment]
LGTM, dummy snippet is working as intended when using latest revision.

Any idea when new tag will be available (in order to avoid using commit hash in go.mod ?)

Thanks everyone (@Sadzeih @alexjomin) for merging this so fast, cheers!

**Comment by alexjomin** [comment]
Tag `1.5.0` pushed!
